# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java Deploy the app to vps server

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn clean install
      - name: Upload application
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          source: "target/myspringbootapp-0.0.1-SNAPSHOT.jar"
          target: "~/source"
      - name: Start Service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          port: 22
          script: |
            #!/bin/bash
            sudo /etc/init.d/my-app stop
               mv ~/source/target/myspringbootapp-0.0.1-SNAPSHOT.jar ~/source/myspringbootapp-0.0.1-SNAPSHOT-old.jar
               mv ~/source/target/myspringbootapp-0.0.1-SNAPSHOT-latest.jar ~/source/target/myspringbootapp-0.0.1-SNAPSHOT.jar
               sudo rm -rf /etc/init.d/build
               sudo ln -s -f ~/source/target/myspringbootapp-0.0.1-SNAPSHOT.jar /etc/init.d/build
               sudo /etc/init.d/build start
               rm ~/source/myspringbootapp-0.0.1-SNAPSHOT-old.jar


